---
- name: Log into private registry and force re-authorization
  docker_login:
    registry: "{{ docker_registry }}"
    username: "{{ docker_registry_login }}"
    password: "{{ docker_registry_password }}"
    reauthorize: yes