name: Default CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: microservice

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: microservice
      
    - name: Build docker image
      run: ./gradlew docker
      working-directory: microservice
      
    - name: Docker login
      run: docker login docker.pkg.github.com --username matkov --password ${{ secrets.GITHUB_TOKEN }}
      working-directory: microservice
  
    - name: Push docker images
      run: ./gradlew dockerTagsPush
      working-directory: microservice
      
 
